logging-to-file = true       
enable-magisk-update = true
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube-Extended]
app-name = "YouTube"
build-mode = "module"
version = "auto"
include-stock = "true" 
excluded-patches = "'Custom branding YouTube name' 'Custom branding icon MMT' 'Custom branding icon Revancify blue' 'Custom branding icon Revancify red' 'Custom package name' 'Enable debug logging' 'MicroG support' 'Theme'"
included-patches = "'MaterialYou'" 
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
