logging-to-file = true   
enable-magisk-update = true 
build-mindetach-module = true
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

[YouTube-Extended]
app-name = "YouTube"
build-mode = "module"
include-stock = "false"
excluded-patches = "custom-branding-icon-revancify-blue custom-branding-youtube-name microg-support theme"                                                 
included-patches = "materialyou"                                                   
version = "auto"   
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"