logging-to-file = true   
enable-magisk-update = true 
build-mindetach-module = true

[YouTube]
app-name = "YouTube"
build-mode = "module"
include-stock = "true"
excluded-patches = "custom-branding enable-debugging premium-heading theme vanced-microg-support"                                                                                             
version = "auto"   
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"